# Generated by Django 3.0.7 on 2020-06-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_rsvp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rsvp',
        ),
    ]
