# Generated by Django 3.0.7 on 2020-06-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_rsvp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Responses',
        ),
    ]
