# Generated by Django 3.0.7 on 2020-06-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_auto_20200621_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rsvp',
        ),
    ]
