# Generated by Django 3.0.7 on 2020-06-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0008_auto_20200621_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='attending',
            new_name='please_check_if_you_are_able_to_attend',
        ),
    ]
