# Generated by Django 3.0.7 on 2020-06-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0009_auto_20200621_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='last_name',
        ),
    ]
